### ISSUE TITLE
Translate www.ruby-lang.org post

### ISSUE THREAD

**Issue by joneslee85** [ruby-vietnam/hacknite#19]
Có ai muốn giúp dịch các bài sau ra tiếng Việt không nhỉ?

- [x] https://www.ruby-lang.org/en/news/2015/02/23/support-for-ruby-1-9-3-has-ended/
- [x] https://www.ruby-lang.org/en/news/2015/02/25/ruby-2-0-0-p643-is-released/
- [x] https://www.ruby-lang.org/en/news/2015/03/03/ruby-2-2-1-released/
- [x] https://www.ruby-lang.org/en/news/2015/03/06/google-summer-of-code-2015/

**Comment by nguyenducgiang** [comment]
Em đăng kí. Nhưng chưa rõ cách làm thế nào?

**Comment by joneslee85** [comment]
@nguyenducgiang em phải clone repo ruby/www.ruby-lang.org, tạo branch mới, và copy file từ thư mục en vào thư mục vi, dịch nó ra, rồi nộp PR

em chọn dịch bài nào để anh ghi vào

**Comment by nguyenducgiang** [comment]
Cả 4 luôn đi ạ.
