### ISSUE TITLE
Thành lập RubyGirls Việt Nam

### ISSUE THREAD

**Issue by joneslee85** [ruby-vietnam/hacknite#20]
Mọi người chắc hẳn đã nghe đến [RailsGirls](http://railsgirls.com/). RailsGirls là một loạt các sự kiện được tổ chức trên thế giới, thường là 2 ngày cuối tuần, tại đây các bạn nữ sẽ được hướng dẫn cơ bản về Ruby và Rails, và hi vọng thông qua đó khơi dậy được niềm đam mêm lập trình của các bạn. Tại sao lại có những sự kiện này? Lí do là có một sự chênh lệch lớn về tỉ lệ nam nữ trong cộng đồng lập trình, và riêng ở Việt Nam thì các bạn nữ thường hay bị phân biệt nếu chọn nghiệp lâp trình. Hơn thế cũng có một thực trạng là có chênh lệch về mặt lượng bổng và cơ hội cho phái nữ trong hầu hết các lĩnh vực IT. Cũng chính vì thế mà nhiều bạn nữ ngại không chọn lập trình mặc dù rất thích. Mình mong thông qua các sự kiện sẽ giúp thay đổi các nhìn của XH về vấn đề tiêu cực này.

## Việc cần làm

* [ ] Đăng ký thành lập tổ chức phi lợi nhuận
* [ ] Đăng ký tên miền và tạo trang chủ
* [ ] Phiên dịch các tutorial phù hợp về Ruby/Rails/Lotus/Sinatra qua tiếng Việt
* [ ] Thu thập thông tin các bạn nữ quan tâm
* [ ] Thành lập BĐH của tổ chức
* [ ] Kêu gọi và thu thập các bạn xung phong làm mentor/coach
* [ ] Dịch http://guides.railsgirls.com/ qua tiếng Việt

**Comment by mymai91** [comment]
:+1:

**Comment by vinhngl** [comment]
:+1:

**Comment by dieunb** [comment]
:+1:

**Comment by mymai91** [comment]
Sinh viên có thể tham gia hoạt động này được không ad? Có yêu cầu gì khác về kiến thức không ạ?
Ở trường đại học mình đã theo học thì không hướng đến ngôn ngữ này. Mình muốn biết rõ để giới thiệu hoạt động này đến thầy cô và các bạn sinh viên ở trường mình.

**Comment by nguyenngoc2505** [comment]
:+1:

**Comment by trongbq** [comment]
:+1:

**Comment by joneslee85** [comment]
@mymai91 được chứ em, không phân biệt là sinh viên hay đã đi làm hay chưa, miễn là có quan tâm là đc.

**Comment by mymai91** [comment]
Dạ, cảm ơn anh ạ

**Comment by nguyenducgiang** [comment]
:+1:

**Comment by dieunb** [comment]
Anh @joneslee85, mentor/coach sẽ làm những việc gì? Và điều kiện cần để có thể đăng ký trở thành mentor/coach?

**Comment by pddo** [comment]
:+1:

**Comment by pddo** [comment]
Ở dự án của mình, các bạn tester thường là nữ, và hiện với nhu cầu về auto test rất cao nhưng kỹ năng lập trình liên quan đến Ruby của các bạn vẫn chưa đủ đáp ứng. Khi mình hỏi thì nhiều bạn tester trả lời rất thích tìm hiểu về Ruby và viết autotest để tăng hiệu suất nhưng gặp nhiều trở ngại lúc bắt đầu.
Nếu thành lập được cộng đồng RailsGirl thì sẽ là nơi rất tốt cho các bạn ấy tham gia trao dồi kỹ năng cũng như nâng cao cơ hội nghề nghiệp.

**Comment by joneslee85** [comment]
@dieunb điều kiện của mentor hay coach là có kinh nghiệm và vững cơ bản Ruby để có thể trợ giúp các bạn nữ trong sự kiện vd trả lời câu hỏi, giải thích bài tập, vv.

**Comment by joneslee85** [comment]
@pddo vâng, bạn nào cũng được, tester hay không và cho dù là làm trái nghề liên quan IT cũng được, chỉ cần họ có quyết tâm để hoàn tất 2 ngày

**Comment by LeoTeam** [comment]
:+1:

**Comment by DonDinhIT** [comment]
:+1:
