### ISSUE TITLE
Thêm chức năng đăng ký thành viên vào trang ruby.org.vn

### ISSUE THREAD

**Issue by joneslee85** [ruby-vietnam/hacknite#21]
Vấn đề hiện nay là không biết được số thành viên thật và số bot là bao nhiêu nếu dựa trên số likes trên FB group. Mình có đề xuất ý tưởng là thêm vào 1 trang đăng ký thành viên, yêu cầu thành viên phải đăng nhập và Github OAuth để hoàn tất thủ tục.

**Comment by mymai91** [comment]
:+1:

**Comment by nguyenducgiang** [comment]
Có thể dùng Devise, config Oauth cho Github.

**Comment by vumanhcuongit** [comment]
repo của mình tại hacknite đêm qua, https://github.com/vumanhcuongit/hacknite-ruby-vn-github-oauth

**Comment by joneslee85** [comment]
Thanks Cường
