### ISSUE TITLE
Tạo mailing list cho nhóm

### ISSUE THREAD

**Issue by joneslee85** [ruby-vietnam/hacknite#22]
Hiện nay một số bạn có phản hồi là không thường xuyen vào đọc FB và các bài viết thường bị cuốn trôi về sau nên dễ bị bỏ qua các bài hay. Mình có ý kiến là tạo một mailing list để các thành viên nào quan tâm có thể subscribe để nhận được tổng kết các bạn đã đăng trên FB group trong tuần.

**Comment by vinhngl** [comment]
:+1:

**Comment by dieunb** [comment]
:+1:

**Comment by hiendinhngoc** [comment]
:+1:

**Comment by hiendinhngoc** [comment]
:+1:

**Comment by nguyenducgiang** [comment]
:+1:

**Comment by pddo** [comment]
:+1:

**Comment by crashbell** [comment]
:+1:

**Comment by baothi** [comment]
:+1:
