### ISSUE TITLE
Dịch thuật các tin mới nhất trên ruby-lang.org

### ISSUE THREAD

**Issue by joneslee85** [ruby-vietnam/hacknite#25]
Hiện có 4 bài mới cần có người phiên dịch:

- [x] https://www.ruby-lang.org/en/news/2015/04/13/ruby-openssl-hostname-matching-vulnerability/
- [x] https://www.ruby-lang.org/en/news/2015/04/13/ruby-2-2-2-released/
- [x] https://www.ruby-lang.org/en/news/2015/04/13/ruby-2-1-6-released/
- [x] https://www.ruby-lang.org/en/news/2015/04/13/ruby-2-0-0-p645-released/

**Comment by mymai91** [comment]
Team Leo nhận nhiệm vụ dich này.

**Comment by DonDinhIT** [comment]
:+1:

**Comment by joneslee85** [comment]
vậy thì chia nhau ra thôi, mỗi người dịch 1 bài

**Comment by DonDinhIT** [comment]
ok anh :)

**Comment by LeoTeam** [comment]
Done. Đã create PR

**Comment by joneslee85** [comment]
https://github.com/ruby/www.ruby-lang.org/pull/1052
