### ISSUE TITLE
Calculate similarity between two contents (in Vietnamese)

### ISSUE THREAD

**Issue by aletuan** [ruby-vietnam/hacknite#26]
I would like to ask an algorithm to calculate the similarity in content between two random article.
This function is useful to apply in some "suggestion" function in News, Book store application. How do you think ?

**Comment by huydx** [comment]
this is quite an ambiguous question. "similarity" is interpreted by many ways, but normally we use cosine distance to calculate the distance in words frequency, which you can find a sample in here: https://www.andrew.cmu.edu/course/15-121/labs/HW-4%20Document%20Distance/lab.html
