### ISSUE TITLE
An out of the box authentication gem 

### ISSUE THREAD

**Issue by hieuk09** [ruby-vietnam/hacknite#27]
This gem should not couple to Rails like devise, and be able to work with some popular ruby framework like Rails, Lotus, Sinatra, ...

**Comment by joneslee85** [comment]
hay đấy, vậy có dựa trên warden không em?

**Comment by hieuk09** [comment]
Em nghĩ có lẽ vẫn dựa trên warden cho đơn giản.

**Comment by unrealhoang** [comment]
:+1:

—
